### ISSUE TITLE
EfSchemaCompare: Wrong difference reported on generated value

### ISSUE THREAD

**Issue by novar0** [JonPSmith/EfCore.TestSupport#2]
Entity:
public class NormativeReference
{
  [Key, MaxLength (50)]
  public string NormativeReferenceId { get; set; }
  public string Name { get; set; }
}

SQL (SQL Server 2014):
CREATE TABLE [dbo].[NormativeReferences] (
    [NormativeReferenceId] NVARCHAR (50)  NOT NULL,
    [Name]                 NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_NormativeReferences] PRIMARY KEY CLUSTERED ([NormativeReferenceId] ASC)
);

CompareEfWithDb returns:
DIFFERENT: NormativeReference->Property 'NormativeReferenceId', value generated. Expected = OnAdd, found = Never

**Comment by JonPSmith** [comment]
Hi @novar0,

I have reproduced this issue, but I couldn't find a way to detect the situation in EF Core. I have therefore [raised an issue](https://github.com/aspnet/EntityFrameworkCore/issues/10415) with the EF Core team. Once I have their feedback I will fix the problem.

Thanks again for bringing this issue up.

**Comment by JonPSmith** [comment]
Fixed in version 1.1.3 of NuGet
