### ISSUE TITLE
Ability to pass paramater to CreateOptions

### ISSUE THREAD

**Issue by CrahunGit** [JonPSmith/EfCore.TestSupport#24]
The problem is I need to add to the dbcontextoptionsbuilder the net topology options but currently I can't because all methods don't have the proper lambda like the constructor while using the adddbcontext option

**Comment by JonPSmith** [comment]
Not sure if that is worth adding. You can do that yourself. Its not that hard.

**Comment by CrahunGit** [comment]
Thank you, John. I’ve done it creating the connection by hand as Microsoft docs said. Not too much work as you said.

**Comment by JonPSmith** [comment]
BTW. If you want a unique named database then EfCore.TestSupport has a `GetUniqueDatabaseConnectionString` - see [docs here](https://github.com/JonPSmith/EfCore.TestSupport/wiki/3b.-Creating-connection-strings).
