### ISSUE TITLE
Method not found: 'Microsoft.EntityFrameworkCore.WarningBehavior 

### ISSUE THREAD

**Issue by Abbassiiheb** [JonPSmith/EfCore.TestSupport#31]
Microsoft.EntityFrameworkCore.Diagnostics.EventDefinitionBase.GetLogBehavior(Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger`1<!!0>)'.

**Comment by JonPSmith** [comment]
Hi @Abbassiiheb,

Not sure what you saying. Can you add:
* The code you were running, and stacktrace of the exception
* The version of EfCore.TestSupport you have
* What .NET Core version you have.
* What platform you are running on: Windows, Linus etc.
