### ISSUE TITLE
Missing primary key in SQL table throws NullReferenceException

### ISSUE THREAD

**Issue by adamjez** [JonPSmith/EfCore.TestSupport#32]
Hi,

I ran into minor bug with nuget EfCore.TestSupport 3.1.1 version (latest).

I get unhandled `NullReferenceException` thrown in ` Stage1Comparer.CompareModelToDatabase(DatabaseModel databaseModel) line 297`.

The problem occurs when a primary key **is missing in a SQL table** but is present in EF Core model.

repro:
```SQL
CREATE TABLE [MyEntities] (
    [MyEntityId] int NOT NULL
);
```
```C#
public class MyEntity
{
    public int MyEntityId { get; set; }
}
...
public DbSet<MyEntity> MyEntities { get; set; }
```

I would expect a warning message explaining missing **primary key** in a SQL table
___
I found out that there is similar issue #8 but is *closed*. The issue was fixed with check for primary key in EF Core model. IMO similar check should be for SQL model.

**Comment by JonPSmith** [comment]
Hi @adamjez,

Yep, I see that.  I won't fix it now but I've added it to the ToDo list. I have some other things to look at first.

Thanks for letting me know.

**Comment by JonPSmith** [comment]
I have put a fix in for missing primary keys in the database, but can you check this as my [unit test](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/Test/UnitTests/EfSchemaCompare/Issue032Tests.cs) didn't fail in the same way your code its.

I will close for now. Please confirm that its working for you.

**Comment by LouisMilesRH** [comment]
Working perfectly for me now 👍

**Comment by adamjez** [comment]
I tested it and it resolved the issue. Now I'm getting detailed assert message  :-) Thank you!

**Comment by JonPSmith** [comment]
Thanks @LouisMilesRH and @adamjez for your feedback. Glad it solved your problem @adamjez and partly helped you @LouisMilesRH
