### ISSUE TITLE
Support EF Core 3.1 for .NET Standard 2.0

### ISSUE THREAD

**Issue by jahav** [JonPSmith/EfCore.TestSupport#38]
EF Core [3.1](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#ef-core-30-targets-net-standard-21-rather-than-net-standard-20) works on .NET Standard 2.0 (i.e. you can use it along with the .NET Framework).

The library doesn't with .NET Framework 4.7.2 and EF Core 3.1, because the [project references](https://github.com/JonPSmith/EfCore.TestSupport/blob/a5c894303341d3a159861d2e8fe0d2b8688833d2/TestSupport/TestSupport.csproj#L22) EF Core 2.0 for .NET Standard 2.0, although it can use 3.0.

Migration from .NET Framework to .NET Core 5.0 is going to be a long one and it would be good to support framework for some time.

When I tried it, it failed because of [different factory methods](https://github.com/JonPSmith/EfCore.TestSupport/blob/a5c894303341d3a159861d2e8fe0d2b8688833d2/TestSupport/EfSchemeCompare/CompareEfSql.cs#L149) in 2.0 and 3.1

**Comment by JonPSmith** [comment]
Hi @jahav,

Yep, sorry about that - here's why it happened. I converted this library as soon as EF Core 3.0 was out and 3.0 required  .NET Standard 2.1. Then they downgraded to .NET Standard 2.0 in EF Core 3.1, but my library used the NET standard as the determinate on what version of EF Core it supports.

Going forward with 5.0 I can't make my libraries self-selecting by the .NET Standard any more so I will have to match by version numbers. That's going to be a massive job to redo all my EfCore libraries with different versions and features. And I'm not going to do that until EF Core 5 is out, and I need to finish the update of my book too.

**Comment by JonPSmith** [comment]
I had a look at this when I was building the EF Core 5 version and I can't fix this easily.
