### ISSUE TITLE
Only Supports Sqlite and SQL Server

### ISSUE THREAD

**Issue by pha3z** [JonPSmith/EfCore.TestSupport#40]
Can the readme and wiki be updated to have obvious upfront statements about supported databases somewhere?

I completely failed to check supported providers.  I was totally excited to use this until I got the lovely "This is not a database provider that we currently support." ::SAD_FACE::

Is the level of effort required to support other providers such as Postgres too steep?

**Comment by JonPSmith** [comment]
Hi @pha3z,

You must be referring to `CompareEfSql` and it does support other database providers (I will change the message to say that). 

To make it work with another database provider you need to use the version which takes in the IDesignTimeServices for the database provider you need, e.g. `comparer.CompareEfWithDb<SqlServerDesignTimeServices>(context);` as shown in [this section of the docs](https://github.com/JonPSmith/EfCore.TestSupport/wiki/How-to-use-the-EfSchemaCompare-feature#using-with-database-provider-not-installed-in-efcoretestsupport-library).

I'm going to leave this open to remind me to change the error message.

**Comment by pha3z** [comment]
Firstly, AWESOME! I'm so happy to hear I can use this with Postgres. :)  Thank you!  I'm super excited to use this library!

Secondly, I read that section of the doc, and I get it now.  I always forget how crucial it is to recognize that there are different providers for a lot of databases.

Thirdly, I had never even heard of the "DesignTimeServices" stuff until now.  I read these docs and found them unhelpful: https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/services
and here https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.design.idesigntimeservices?view=efcore-3.1

Can you provide more guidance on how to make this work?

**UPDATE:  Nevermind. I was really overthinking it. I didn't realize I literally just plugin the magic interface for my provider in that one-liner.  I got it to work.**

It still saddens me that the MSDN documentation leaves me feeling pretty in the dark.

**Comment by pha3z** [comment]
I've been trying to figure out how to use NpgsqlDesignTimeServices but so far I'm concerned this won't even work for me.

It might be worth mentioning that I don't follow the Microsoft Happy Path on much of anything... which might be part of my confusion here.  Of course, I would think this should be expected since a lot of people who want to use this library have no intention of following the Microsoft Happy Path. :)

My custom DbContext is setup like this:

` 
public GameDbContext(ZetaDbConfig dbConfig)
{
    dbConfig = dbConfig ?? throw new ArgumentNullException("dbConfig cannot be null");
}

protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            switch (_dbConfig.DbEngine)
            {
                case DbEngine.SQLITE:
                    optionsBuilder.UseSqlite(_dbConfig.ConnString); break;
                case DbEngine.MYSQL:
                    optionsBuilder.UseMySql(_dbConfig.ConnString); break;
                case DbEngine.POSTGRES:
                    optionsBuilder.UseNpgsql(_dbConfig.ConnString); break;
                default:
                    throw new NotImplementedException($"Unhandled dbtype {_dbConfig.DbEngine}");
            }
}`

ZetaDbConfig simply indicates which optionsUse method to call and the connection string.

The rest of my tooling is all pretty much custom.  I manage database connections myself and build my own factories for newing up DbContexts on the fly.

I thought this might shed a little light on where I'm coming from so you can understand where the gap might be for me.

**Comment by JonPSmith** [comment]
Glad that it worked.

BTW The "DesignTimeServices" are needed in some cases where you need a DbContext to create a migration - see [this page in the EF Core docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation).

All the best with your project.

**Comment by JonPSmith** [comment]
Hi @pha3z,

Just to say I have split the EfSchemaCompare out into its [own project](https://github.com/JonPSmith/EfCore.SchemaCompare) and added a lots of features/fixes, especially around EF Core 5 new features. 

I have also updated the exception message to list what you need to do for database providers that aren't built into the library.
