### ISSUE TITLE
Support EF Core 5

### ISSUE THREAD

**Issue by CrahunGit** [JonPSmith/EfCore.TestSupport#42]
Currently tests are failing becouse seems that library tries to call internal EF Core method that are not available now. Do you plan to update the library?

**Comment by JonPSmith** [comment]
Hi @CrahunGit,

Just to let you know that there is a version of EfCore.TestSupport out now, but I recommend you read the [Version 5 upgrade doc](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/Version5UpgradeDocs.md) as there are a lot of changes, some of which are breaking changes.

**Comment by CrahunGit** [comment]
Thank you @JonPSmith. I'm going to take a look.
