### ISSUE TITLE
Hardcoded role name `postgres`

### ISSUE THREAD

**Issue by kolpav** [JonPSmith/EfCore.TestSupport#48]
FYI `postgres` is not always current `role_name` using value returned from `SELECT current_user;` might be more appropriate.

https://github.com/JonPSmith/EfCore.TestSupport/blob/994cc0a845614805444412732685a0b4c1814930/TestSupport/EfHelpers/Internal/PostgreSqlDropSchemaEnsureClean.cs#L36

**Comment by JonPSmith** [comment]
Hi @kolpav,

I'm not an postgres expert and I got this code from @roji.

@roji, can you have a look at this for me.

**Comment by roji** [comment]
Yeah, that makes sense - replacing `TO postgres` with `TO current_user` should do it.

**Comment by JonPSmith** [comment]
Thanks @roji. I'll add that to my list of things to do

**Comment by JonPSmith** [comment]
Fixed in version 5.2.2
