### ISSUE TITLE
Use secrets.json

### ISSUE THREAD

**Issue by tschennie** [JonPSmith/EfCore.TestSupport#55]
For our integration tests, we created a DbContext like this:

```
DbContextOptions<TestDbContext>? options = this.CreateUniqueMethodOptions<TestDbContext>();
await using TestDbContext dbContext = new(options);
```

How is it possible to use the connection string from the secrets.json?

**Comment by JonPSmith** [comment]
Hi @tschennie,

The `CreateUniqueMethodOptions<TContext>` and other similar use the normal .NET access the project's configuration. This means if you [Enable secret storage](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets#enable-secret-storage) on the your test project, then you can set up a secret that overrides the appsettings.json version. 

The connection strings names can be found [here](https://github.com/JonPSmith/EfCore.TestSupport/wiki/Creating-connection-strings#specifying-the-base-database-connection-string-for-sql-server-and-postgresql).
