### ISSUE TITLE
Columns checks are case sensitive

### ISSUE THREAD

**Issue by JeanCollas** [JonPSmith/EfCore.TestSupport#9]
As SQL Server is in most cases case insensitive for its structure, it may be a good idea to make the checks case insensitive by default?

Currently a property named `Metadata` will not match a column named `MetaData`, and the script will returns that the column is missing.

**Comment by JonPSmith** [comment]
Sorry @JeanCollas,

This came in when I was mega busy and I forgot to get back to this. I'm still busy so I will add this to the backlog. 

I'll most likely add a config to control it, with a default of case insensitive, as you can change a SQL Server to be case sensitive.

**Comment by JeanCollas** [comment]
Good news. 

I still use your great tool, slightly modified for my needs. 
I initially planned to build the same, but yours does the work :) 
I hope someday to release opensource part of what I used it for.

**Comment by JonPSmith** [comment]
Great, and sorry for the delay. I happy to say that after writing my book and libraries I have a stream of people wanting to employ me to design or fix systems. Really interesting work (and good pay) but doesn't leave me much time to keep my five libraries up to date :(

**Comment by JeanCollas** [comment]
I am reviewing some of your libs, and I am realizing that I am building the same kind of tools ^^
Any way to contact you and have a chat?

**Comment by JonPSmith** [comment]
Hi @JeanCollas,

That would be good, although I have to warn you I am very busy. 

Send me your email via the [contact page](https://www.thereformedprogrammer.net/contact/) on my tech blog, as I don't want to show my email online otherwise I will get (more) spam.

**Comment by JonPSmith** [comment]
Hi @JeanCollas,

I have just released version 2.0.0 where you can use case insensitive matching. See the `CaseComparer` property in the [CompareEfSqlConfig](https://github.com/JonPSmith/EfCore.TestSupport/blob/master/TestSupport/EfSchemeCompare/CompareEfSqlConfig.cs) class. 

I hope that helps you.
